// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: tayzhangtest.proto

package taylorzhtestpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tayzhangtest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tayzhangtest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_tayzhangtest_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tayzhangtest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_tayzhangtest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_tayzhangtest_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoadTestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *LoadTestRequest) Reset() {
	*x = LoadTestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tayzhangtest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestRequest) ProtoMessage() {}

func (x *LoadTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tayzhangtest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestRequest.ProtoReflect.Descriptor instead.
func (*LoadTestRequest) Descriptor() ([]byte, []int) {
	return file_tayzhangtest_proto_rawDescGZIP(), []int{2}
}

func (x *LoadTestRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type LoadTestReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode int32 `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *LoadTestReply) Reset() {
	*x = LoadTestReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tayzhangtest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadTestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestReply) ProtoMessage() {}

func (x *LoadTestReply) ProtoReflect() protoreflect.Message {
	mi := &file_tayzhangtest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestReply.ProtoReflect.Descriptor instead.
func (*LoadTestReply) Descriptor() ([]byte, []int) {
	return file_tayzhangtest_proto_rawDescGZIP(), []int{3}
}

func (x *LoadTestReply) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

type LoadTestMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadTestMetricsRequest) Reset() {
	*x = LoadTestMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tayzhangtest_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadTestMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestMetricsRequest) ProtoMessage() {}

func (x *LoadTestMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tayzhangtest_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestMetricsRequest.ProtoReflect.Descriptor instead.
func (*LoadTestMetricsRequest) Descriptor() ([]byte, []int) {
	return file_tayzhangtest_proto_rawDescGZIP(), []int{4}
}

type LoadTestMetricsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode map[int64]int64 `protobuf:"bytes,1,rep,name=retCode,proto3" json:"retCode,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *LoadTestMetricsReply) Reset() {
	*x = LoadTestMetricsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tayzhangtest_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadTestMetricsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestMetricsReply) ProtoMessage() {}

func (x *LoadTestMetricsReply) ProtoReflect() protoreflect.Message {
	mi := &file_tayzhangtest_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestMetricsReply.ProtoReflect.Descriptor instead.
func (*LoadTestMetricsReply) Descriptor() ([]byte, []int) {
	return file_tayzhangtest_proto_rawDescGZIP(), []int{5}
}

func (x *LoadTestMetricsReply) GetRetCode() map[int64]int64 {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type LoadTestClearRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoadTestClearRequest) Reset() {
	*x = LoadTestClearRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tayzhangtest_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadTestClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestClearRequest) ProtoMessage() {}

func (x *LoadTestClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tayzhangtest_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestClearRequest.ProtoReflect.Descriptor instead.
func (*LoadTestClearRequest) Descriptor() ([]byte, []int) {
	return file_tayzhangtest_proto_rawDescGZIP(), []int{6}
}

type LoadTestClearReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode int32 `protobuf:"varint,1,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *LoadTestClearReply) Reset() {
	*x = LoadTestClearReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tayzhangtest_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadTestClearReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTestClearReply) ProtoMessage() {}

func (x *LoadTestClearReply) ProtoReflect() protoreflect.Message {
	mi := &file_tayzhangtest_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTestClearReply.ProtoReflect.Descriptor instead.
func (*LoadTestClearReply) Descriptor() ([]byte, []int) {
	return file_tayzhangtest_proto_rawDescGZIP(), []int{7}
}

func (x *LoadTestClearReply) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

var File_tayzhangtest_proto protoreflect.FileDescriptor

var file_tayzhangtest_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x61, 0x79, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x74, 0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a, 0x68, 0x74, 0x65,
	0x73, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x25,
	0x0a, 0x0f, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x29, 0x0a, 0x0d, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x22, 0x18, 0x0a, 0x16, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9d, 0x01, 0x0a, 0x14, 0x4c,
	0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x49, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x74, 0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a, 0x68, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x1a, 0x3a,
	0x0a, 0x0c, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x6f,
	0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x2e, 0x0a, 0x12, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6c,
	0x65, 0x61, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x32, 0xcf, 0x02, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x42,
	0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x1a, 0x2e, 0x74, 0x61, 0x79,
	0x6c, 0x6f, 0x72, 0x7a, 0x68, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a,
	0x68, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x08, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x2e, 0x74, 0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a, 0x68, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f,
	0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x74, 0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a, 0x68, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x61,
	0x64, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x0f,
	0x4c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12,
	0x24, 0x2e, 0x74, 0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a, 0x68, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4c,
	0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74, 0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a, 0x68,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x0d, 0x4c,
	0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x12, 0x22, 0x2e, 0x74,
	0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a, 0x68, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x6f, 0x61, 0x64,
	0x54, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x74, 0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a, 0x68, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x4c, 0x6f, 0x61, 0x64, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x79, 0x78,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x79, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x74, 0x65, 0x73,
	0x74, 0x2f, 0x74, 0x61, 0x79, 0x6c, 0x6f, 0x72, 0x7a, 0x68, 0x74, 0x65, 0x73, 0x74, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tayzhangtest_proto_rawDescOnce sync.Once
	file_tayzhangtest_proto_rawDescData = file_tayzhangtest_proto_rawDesc
)

func file_tayzhangtest_proto_rawDescGZIP() []byte {
	file_tayzhangtest_proto_rawDescOnce.Do(func() {
		file_tayzhangtest_proto_rawDescData = protoimpl.X.CompressGZIP(file_tayzhangtest_proto_rawDescData)
	})
	return file_tayzhangtest_proto_rawDescData
}

var file_tayzhangtest_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tayzhangtest_proto_goTypes = []interface{}{
	(*HelloRequest)(nil),           // 0: taylorzhtest.HelloRequest
	(*HelloReply)(nil),             // 1: taylorzhtest.HelloReply
	(*LoadTestRequest)(nil),        // 2: taylorzhtest.LoadTestRequest
	(*LoadTestReply)(nil),          // 3: taylorzhtest.LoadTestReply
	(*LoadTestMetricsRequest)(nil), // 4: taylorzhtest.LoadTestMetricsRequest
	(*LoadTestMetricsReply)(nil),   // 5: taylorzhtest.LoadTestMetricsReply
	(*LoadTestClearRequest)(nil),   // 6: taylorzhtest.LoadTestClearRequest
	(*LoadTestClearReply)(nil),     // 7: taylorzhtest.LoadTestClearReply
	nil,                            // 8: taylorzhtest.LoadTestMetricsReply.RetCodeEntry
}
var file_tayzhangtest_proto_depIdxs = []int32{
	8, // 0: taylorzhtest.LoadTestMetricsReply.retCode:type_name -> taylorzhtest.LoadTestMetricsReply.RetCodeEntry
	0, // 1: taylorzhtest.Greeter.SayHello:input_type -> taylorzhtest.HelloRequest
	2, // 2: taylorzhtest.Greeter.LoadTest:input_type -> taylorzhtest.LoadTestRequest
	4, // 3: taylorzhtest.Greeter.LoadTestMetrics:input_type -> taylorzhtest.LoadTestMetricsRequest
	6, // 4: taylorzhtest.Greeter.LoadTestClear:input_type -> taylorzhtest.LoadTestClearRequest
	1, // 5: taylorzhtest.Greeter.SayHello:output_type -> taylorzhtest.HelloReply
	3, // 6: taylorzhtest.Greeter.LoadTest:output_type -> taylorzhtest.LoadTestReply
	5, // 7: taylorzhtest.Greeter.LoadTestMetrics:output_type -> taylorzhtest.LoadTestMetricsReply
	7, // 8: taylorzhtest.Greeter.LoadTestClear:output_type -> taylorzhtest.LoadTestClearReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tayzhangtest_proto_init() }
func file_tayzhangtest_proto_init() {
	if File_tayzhangtest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tayzhangtest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tayzhangtest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tayzhangtest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadTestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tayzhangtest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadTestReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tayzhangtest_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadTestMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tayzhangtest_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadTestMetricsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tayzhangtest_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadTestClearRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tayzhangtest_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadTestClearReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tayzhangtest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tayzhangtest_proto_goTypes,
		DependencyIndexes: file_tayzhangtest_proto_depIdxs,
		MessageInfos:      file_tayzhangtest_proto_msgTypes,
	}.Build()
	File_tayzhangtest_proto = out.File
	file_tayzhangtest_proto_rawDesc = nil
	file_tayzhangtest_proto_goTypes = nil
	file_tayzhangtest_proto_depIdxs = nil
}
